server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${postgres_server}:${postgres_port}/weatherdb
    hikari:
      username: ${postgres_username}
      password: ${postgres_password}

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.data.redis: DEBUG
